version: '3.6'

services:
  web:
    image: dukaanweb
    build:
      context: .
      dockerfile: dukaan.web/Dockerfile
    ports:
      - "51212:80"
    secrets:
      - db_connection_string
      - db_dukaan_web_user_password
    depends_on:
      - database
    networks:
      - webnet
  database:
    image: dukaandatabase
    build:
      context: .
      dockerfile: dukaan.database/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_postgres_user_password
      POSTGRES_INITDB_ARGS: --data-checksums
    secrets:
      - db_dukaan_web_user_password
      - db_postgres_user_password
    networks:
      - webnet
  databaseadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - docker/environment_variables/pgadmin.env
    depends_on:
      - database      
    networks:
      - webnet      
secrets:
  db_connection_string:
    file: docker/secrets/db_connection_string.txt
  db_dukaan_web_user_password:
    file: docker/secrets/db_dukaan_web_user_password.txt
  db_postgres_user_password:
    file: docker/secrets/db_postgres_user_password.txt
networks:
  webnet:
